{{- if .Values.extra_database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timelynotify-server.fullname" . }}-mysql
  labels:
    {{- include "timelynotify-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: >-
    {{ .Values.extra_database.mysql.username }}:{{ .Values.extra_database.mysql.password }}@tcp({{ .Values.extra_database.mysql.host }}:{{ .Values.extra_database.mysql.port }})/{{ .Values.extra_database.mysql.database }}
{{- end }}